include: package:yumemi_lints/dart/2.17/recommended.yaml

linter:
  rules:
    avoid_print: false

    # This project does not use the `meta` package, so it has been disabled.
    avoid_equals_and_hash_code_on_mutable_classes: false
