name: yumemi_lints_tools
sdkPath: .dvm/dart_sdk

packages:
  - tools/**

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
