name: yumemi_lints_tools
sdkPath: .dvm/dart_sdk

packages:
  - check_lint_rules_identity
  - update_lint_rules

command:
  bootstrap:
    environment:
      sdk: ^3.1.0
    dev_dependencies:
      build_runner: ^2.4.7
      custom_lint: ^0.5.8

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
