name: yumemi_lints
description: Customizable Linter library which enforces coding standards and best practice for Flutter/Dart apps, packages and plugins.
version: 2.0.0
repository: https://github.com/yumemi-inc/flutter-yumemi-lints

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  pub_semver: ^2.1.4
  path: ^1.9.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.21.0

topics:
  - lint
  - lints
  - linter
  - analysis
  - code-style
