name: yumemi_lints
description: Customizable Linter library which enforces coding standards and best practice for Flutter/Dart apps, packages and plugins.
version: 2.0.0
repository: https://github.com/yumemi-inc/flutter-yumemi-lints

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: ^2.3.1
  meta: ^1.10.0
  path: ^1.8.1
  pub_semver: ^2.1.4
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.21.4

topics:
  - lint
  - lints
  - linter
  - analysis
  - code-style
