name: yumemi_lints
description: Customizable Linter library which enforces coding standards and best practice for Flutter/Dart apps, packages and plugins.
version: 2.0.0
repository: https://github.com/yumemi-inc/flutter-yumemi-lints

environment:
  sdk: ^3.1.0

topics:
  - lint
  - lints
  - linter
  - analysis
  - code-style
