name: Update Contributors
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  UPDATE_CONTRIBUTORS_BRANCH: update-contributors

jobs:
  add-contributors:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Delete old branch (If it exists)
        run: git push origin --delete ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
        continue-on-error: true
      - name: Create and push new branch
        run: |
          git branch ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
          git push origin ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
      # https://github.com/BobAnkh/add-contributors
      - uses: BobAnkh/add-contributors@de6c43a0c154b093a210d8bdf7ab283aba8452dd # v0.2.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
          PULL_REQUEST: 'main'
          IGNORED_CONTRIBUTORS: 'GitHub Web Flow'
